---
description: "Más información sobre: ' Catch ' no puede aparecer después de ' Finally ' dentro de una instrucción ' Try '"
title: "'Catch' no puede aparecer después de 'Finally' dentro de una instrucción 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ec177fadf2490c3779e0ad3a1f754319e12bd9cc
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/14/2021
ms.locfileid: "100454955"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' no puede aparecer después de 'Finally' dentro de una instrucción 'Try'

Una instrucción `Catch` aparece en el código después del elemento `Finally` que finaliza un bloque de instrucciones `Try` . `Catch` debe aparecer dentro de un bloque de instrucciones `Try...Catch...Finally` .  
  
 **Id. de error:** BC30379  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1. Mueva la instrucción `Catch` a un lugar más adecuado del código.  
  
## <a name="see-also"></a>Vea también

- [Try...Catch...Finally (instrucción)](../language-reference/statements/try-catch-finally-statement.md)
