---
description: "Obtenga más información sobre: no se ha alcanzado nunca el bloque ' Catch '; se <exception> controló anteriormente en la misma instrucción ' Try '"
title: No se alcanzó el bloque 'Catch'; '<exception>' se controla anteriormente en la misma instrucción Try
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: fc52c21f7a319c26b6ca7128c8d2d781db1a58c1
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473026"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>No se alcanzó el bloque 'Catch'; '\<exception>' se controla anteriormente en la misma instrucción Try

Un bloque `Catch` del código no se puede alcanzar porque se controla en un bloque `Try` precedente.  
  
De forma predeterminada, este mensaje es una advertencia. Para más información sobre cómo ocultar las advertencias o cómo tratarlas como errores, vea [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **Identificador de error:** BC42031  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
- Quite la instrucción redundante.  
  
## <a name="see-also"></a>Consulte también

- [Cómo usar el bloque Try/Catch para detectar excepciones](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Utilizar controladores de excepciones filtradas por el usuario](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally (instrucción)](../language-reference/statements/try-catch-finally-statement.md)
