---
description: 'Más información acerca de: excepciones'
title: Excepciones
ms.date: 03/30/2017
ms.assetid: 065205cc-52dd-4f30-9578-b17d8d113136
ms.openlocfilehash: 71cf6a4ac23f7979d0c9137d88f36a45f71783a3
ms.sourcegitcommit: ddf7edb67715a5b9a45e3dd44536dabc153c1de0
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/06/2021
ms.locfileid: "99742464"
---
# <a name="exceptions"></a><span data-ttu-id="b3672-103">Excepciones</span><span class="sxs-lookup"><span data-stu-id="b3672-103">Exceptions</span></span>

<span data-ttu-id="b3672-104">Los flujos de trabajo pueden usar la actividad <xref:System.Activities.Statements.TryCatch> para controlar excepciones que se producen durante la ejecución de un flujo de trabajo.</span><span class="sxs-lookup"><span data-stu-id="b3672-104">Workflows can use the <xref:System.Activities.Statements.TryCatch> activity to handle exceptions that are raised during the execution of a workflow.</span></span> <span data-ttu-id="b3672-105">Se pueden controlar estas excepciones o se pueden volver a producir usando la actividad <xref:System.Activities.Statements.Rethrow>.</span><span class="sxs-lookup"><span data-stu-id="b3672-105">These exceptions can be handled or they can be re-thrown using the <xref:System.Activities.Statements.Rethrow> activity.</span></span> <span data-ttu-id="b3672-106">Las actividades de la sección <xref:System.Activities.Statements.TryCatch.Finally%2A> se ejecutan cuando la sección <xref:System.Activities.Statements.TryCatch.Try%2A> o la sección <xref:System.Activities.Statements.TryCatch.Catches%2A> se hayan completado.</span><span class="sxs-lookup"><span data-stu-id="b3672-106">Activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section completes.</span></span> <span data-ttu-id="b3672-107">Los flujos de trabajo hospedados por una <xref:System.Activities.WorkflowApplication> instancia de también pueden usar el <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> controlador de eventos para controlar las excepciones que no se controlan mediante una <xref:System.Activities.Statements.TryCatch> actividad.</span><span class="sxs-lookup"><span data-stu-id="b3672-107">Workflows hosted by a <xref:System.Activities.WorkflowApplication> instance can also use the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> event handler to handle exceptions that are not handled by a <xref:System.Activities.Statements.TryCatch> activity.</span></span>  
  
## <a name="causes-of-exceptions"></a><span data-ttu-id="b3672-108">Causas de excepciones</span><span class="sxs-lookup"><span data-stu-id="b3672-108">Causes of Exceptions</span></span>  

 <span data-ttu-id="b3672-109">En un flujo de trabajo, las excepciones se pueden generar de las maneras siguientes:</span><span class="sxs-lookup"><span data-stu-id="b3672-109">In a workflow, exceptions can be generated in the following ways:</span></span>  
  
- <span data-ttu-id="b3672-110">Un tiempo de espera de transacciones en <xref:System.Activities.Statements.TransactionScope>.</span><span class="sxs-lookup"><span data-stu-id="b3672-110">A time-out of transactions in <xref:System.Activities.Statements.TransactionScope>.</span></span>  
  
- <span data-ttu-id="b3672-111">Una excepción explícita iniciada por el flujo de trabajo mediante la actividad <xref:System.Activities.Statements.Throw>.</span><span class="sxs-lookup"><span data-stu-id="b3672-111">An explicit exception thrown by the workflow using the <xref:System.Activities.Statements.Throw> activity.</span></span>  
  
- <span data-ttu-id="b3672-112">Una excepción [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] iniciada desde una actividad.</span><span class="sxs-lookup"><span data-stu-id="b3672-112">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] exception thrown from an activity.</span></span>  
  
- <span data-ttu-id="b3672-113">Una excepción iniciada desde el código externo, como bibliotecas, componentes o servicios que se usan en el flujo de trabajo.</span><span class="sxs-lookup"><span data-stu-id="b3672-113">An exception thrown from external code, such as libraries, components, or services that are used in the workflow.</span></span>  
  
## <a name="handling-exceptions"></a><span data-ttu-id="b3672-114">Controlar las excepciones</span><span class="sxs-lookup"><span data-stu-id="b3672-114">Handling Exceptions</span></span>  

 <span data-ttu-id="b3672-115">Si la actividad inicia una excepción y no está controlada, el comportamiento predeterminado es terminar la instancia de flujo de trabajo.</span><span class="sxs-lookup"><span data-stu-id="b3672-115">If an exception is thrown by an activity and is unhandled, the default behavior is to terminate the workflow instance.</span></span> <span data-ttu-id="b3672-116">Si un controlador <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> personalizado está presente, puede invalidar este comportamiento predeterminado.</span><span class="sxs-lookup"><span data-stu-id="b3672-116">If a custom <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is present, it can override this default behavior.</span></span> <span data-ttu-id="b3672-117">Este controlador da al autor de host de flujo de trabajo la oportunidad de proporcionar el control adecuado, como el registro personalizado o la anulación, cancelación o finalización del flujo de trabajo.</span><span class="sxs-lookup"><span data-stu-id="b3672-117">This handler gives the workflow host author an opportunity to provide the appropriate handling, such as custom logging, aborting the workflow, canceling the workflow, or terminating the workflow.</span></span>  <span data-ttu-id="b3672-118">Si un flujo de trabajo produce una excepción no administrada, se invoca el controlador <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>.</span><span class="sxs-lookup"><span data-stu-id="b3672-118">If a workflow raises an exception that is not handled, the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="b3672-119">Se devuelven tres posibles acciones de <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> que determinan el resultado final del flujo de trabajo.</span><span class="sxs-lookup"><span data-stu-id="b3672-119">There are three possible actions returned from <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> which determine the final outcome of the workflow.</span></span>  
  
- <span data-ttu-id="b3672-120">**Cancelar** : una instancia de flujo de trabajo cancelada es una salida correcta de una ejecución de la rama.</span><span class="sxs-lookup"><span data-stu-id="b3672-120">**Cancel** - A cancelled workflow instance is a graceful exit of a branch execution.</span></span> <span data-ttu-id="b3672-121">Puede modelar el comportamiento de cancelación (por ejemplo, con una actividad CancellationScope).</span><span class="sxs-lookup"><span data-stu-id="b3672-121">You can model cancelation behavior (for example, by using a CancellationScope activity).</span></span> <span data-ttu-id="b3672-122">Se invoca el controlador Completed cuando el proceso de cancelación se completa.</span><span class="sxs-lookup"><span data-stu-id="b3672-122">The Completed handler is invoked when the cancellation process completes.</span></span> <span data-ttu-id="b3672-123">Un flujo de trabajo cancelado está en estado Cancelled.</span><span class="sxs-lookup"><span data-stu-id="b3672-123">A cancelled workflow is in the Cancelled state.</span></span>  
  
- <span data-ttu-id="b3672-124">**Terminate** : no se puede reanudar o reiniciar una instancia de flujo de trabajo terminada.</span><span class="sxs-lookup"><span data-stu-id="b3672-124">**Terminate** - A terminated workflow instance cannot be resumed or restarted.</span></span>  <span data-ttu-id="b3672-125">Esto desencadena el evento Completed en el que puede proporcionar una excepción como razón por la que finalizó.</span><span class="sxs-lookup"><span data-stu-id="b3672-125">This triggers the Completed event in which you can provide an exception as the reason it was terminated.</span></span> <span data-ttu-id="b3672-126">Se invoca el controlador Terminated cuando el proceso de finalización se completa.</span><span class="sxs-lookup"><span data-stu-id="b3672-126">The Terminated handler is invoked when the termination process completes.</span></span> <span data-ttu-id="b3672-127">Un flujo de trabajo finalizado está en el estado Faulted.</span><span class="sxs-lookup"><span data-stu-id="b3672-127">A terminated workflow is in the Faulted state.</span></span>  
  
- <span data-ttu-id="b3672-128">**Abort** : las instancias de flujo de trabajo anuladas se pueden reanudar solo si se ha configurado para ser persistentes.</span><span class="sxs-lookup"><span data-stu-id="b3672-128">**Abort** - An aborted workflow instances can be resumed only if it has been configured to be persistent.</span></span>  <span data-ttu-id="b3672-129">Sin persistencia, un flujo de trabajo no se puede reanudar.</span><span class="sxs-lookup"><span data-stu-id="b3672-129">Without persistence, a workflow cannot be resumed.</span></span>  <span data-ttu-id="b3672-130">En el punto en que se anula un flujo de trabajo, se perderá todo el trabajo realizado (en memoria) desde el último punto de persistencia.</span><span class="sxs-lookup"><span data-stu-id="b3672-130">At the point a workflow is aborted, any work done (in memory) since the last persistence point will be lost.</span></span> <span data-ttu-id="b3672-131">Para un flujo de trabajo anulado, se invoca el controlador Aborted usando la excepción como motivo cuando se completa el proceso de anulación.</span><span class="sxs-lookup"><span data-stu-id="b3672-131">For an aborted workflow, the Aborted handler is invoked using the exception as the reason when the abort process completes.</span></span> <span data-ttu-id="b3672-132">Sin embargo, a diferencia de Cancelled y Terminated, no se invoca el controlador Completed.</span><span class="sxs-lookup"><span data-stu-id="b3672-132">However, unlike Cancelled and Terminated, the Completed handler is not invoked.</span></span> <span data-ttu-id="b3672-133">Un flujo de trabajo anulado está en un estado Aborted.</span><span class="sxs-lookup"><span data-stu-id="b3672-133">An aborted workflow is in an Aborted state.</span></span>  
  
 <span data-ttu-id="b3672-134">En el ejemplo siguiente se invoca un flujo de trabajo que produce una excepción.</span><span class="sxs-lookup"><span data-stu-id="b3672-134">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="b3672-135">El flujo de trabajo no controla la excepción y se invoca el controlador de la propiedad <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>.</span><span class="sxs-lookup"><span data-stu-id="b3672-135">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="b3672-136">El objeto <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> se inspecciona para proporcionar información acerca de la excepción y se termina el flujo de trabajo.</span><span class="sxs-lookup"><span data-stu-id="b3672-136">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#1](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#1)]  
  
### <a name="handling-exceptions-with-the-trycatch-activity"></a><span data-ttu-id="b3672-137">Administrar excepciones con la actividad TryCatch</span><span class="sxs-lookup"><span data-stu-id="b3672-137">Handling Exceptions with the TryCatch Activity</span></span>  

 <span data-ttu-id="b3672-138">La administración de excepciones dentro de un flujo de trabajo se realiza mediante la actividad <xref:System.Activities.Statements.TryCatch>.</span><span class="sxs-lookup"><span data-stu-id="b3672-138">Handling exceptions inside a workflow is performed with the <xref:System.Activities.Statements.TryCatch> activity.</span></span> <span data-ttu-id="b3672-139">La actividad <xref:System.Activities.Statements.TryCatch> tiene una colección de <xref:System.Activities.Statements.TryCatch.Catches%2A> de las actividades de <xref:System.Activities.Statements.Catch> que se asocian con un tipo <xref:System.Exception> concreto.</span><span class="sxs-lookup"><span data-stu-id="b3672-139">The <xref:System.Activities.Statements.TryCatch> activity has a <xref:System.Activities.Statements.TryCatch.Catches%2A> collection of <xref:System.Activities.Statements.Catch> activities that are each associated with a specific <xref:System.Exception> type.</span></span> <span data-ttu-id="b3672-140">Si la excepción producida por una actividad incluida en la sección <xref:System.Activities.Statements.TryCatch.Try%2A> de una actividad <xref:System.Activities.Statements.TryCatch> coincide con la excepción de una actividad <xref:System.Activities.Statements.Catch%601> en la colección de <xref:System.Activities.Statements.TryCatch.Catches%2A>, se administrará la excepción.</span><span class="sxs-lookup"><span data-stu-id="b3672-140">If the exception thrown by an activity that is contained in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> activity matches the exception of a <xref:System.Activities.Statements.Catch%601> activity in the <xref:System.Activities.Statements.TryCatch.Catches%2A> collection, then the exception is handled.</span></span> <span data-ttu-id="b3672-141">Si se vuelve a producir explícitamente la excepción o se produce una nueva, esta excepción se pasa a la actividad principal.</span><span class="sxs-lookup"><span data-stu-id="b3672-141">If the exception is explicitly re-thrown or a new exception is thrown then this exception passes up to the parent activity.</span></span> <span data-ttu-id="b3672-142">El siguiente ejemplo de código muestra una actividad <xref:System.Activities.Statements.TryCatch> que administra un objeto <xref:System.ApplicationException> que se produce en la sección <xref:System.Activities.Statements.TryCatch.Try%2A> mediante una actividad <xref:System.Activities.Statements.Throw>.</span><span class="sxs-lookup"><span data-stu-id="b3672-142">The following code example shows a <xref:System.Activities.Statements.TryCatch> activity that handles an <xref:System.ApplicationException> that is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section by a <xref:System.Activities.Statements.Throw> activity.</span></span> <span data-ttu-id="b3672-143">El mensaje de la excepción se escribe en la consola mediante la actividad <xref:System.Activities.Statements.Catch%601> y, a continuación, se escribe un mensaje en la consola de la sección <xref:System.Activities.Statements.TryCatch.Finally%2A>.</span><span class="sxs-lookup"><span data-stu-id="b3672-143">The exception's message is written to the console by the <xref:System.Activities.Statements.Catch%601> activity, and then a message is written to the console in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#33](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#33)]  
  
 <span data-ttu-id="b3672-144">Se ejecutarán las actividades en la sección <xref:System.Activities.Statements.TryCatch.Finally%2A> cuando la sección <xref:System.Activities.Statements.TryCatch.Try%2A> o la sección <xref:System.Activities.Statements.TryCatch.Catches%2A> se hayan completado.</span><span class="sxs-lookup"><span data-stu-id="b3672-144">The activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes.</span></span> <span data-ttu-id="b3672-145">La sección <xref:System.Activities.Statements.TryCatch.Try%2A> se completa correctamente si no se produce ninguna excepción de ella, y la sección <xref:System.Activities.Statements.TryCatch.Catches%2A> se completa correctamente si no se produce o se vuelve a producir ninguna excepción desde ella.</span><span class="sxs-lookup"><span data-stu-id="b3672-145">The <xref:System.Activities.Statements.TryCatch.Try%2A> section successfully completes if no exceptions are thrown from it, and the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes if no exceptions are thrown or rethrown from it.</span></span> <span data-ttu-id="b3672-146">Si se produce una excepción en la sección <xref:System.Activities.Statements.TryCatch.Try%2A> de <xref:System.Activities.Statements.TryCatch> y no está controlada por <xref:System.Activities.Statements.Catch%601> en la sección <xref:System.Activities.Statements.TryCatch.Catches%2A> o si se vuelve a producir desde <xref:System.Activities.Statements.TryCatch.Catches%2A>, las actividades de <xref:System.Activities.Statements.TryCatch.Finally%2A> no se ejecutarán a menos que ocurra algo de lo siguiente.</span><span class="sxs-lookup"><span data-stu-id="b3672-146">If an exception is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> and is either not handled by a <xref:System.Activities.Statements.Catch%601> in the <xref:System.Activities.Statements.TryCatch.Catches%2A> section, or is rethrown from the <xref:System.Activities.Statements.TryCatch.Catches%2A>, the activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> will not be executed unless the one of the following occurs.</span></span>  
  
- <span data-ttu-id="b3672-147">La excepción es detectada por una actividad <xref:System.Activities.Statements.TryCatch> de mayor nivel en el flujo de trabajo, independientemente de si se vuelven a producir desde <xref:System.Activities.Statements.TryCatch> de mayor nivel.</span><span class="sxs-lookup"><span data-stu-id="b3672-147">The exception is caught by a higher level <xref:System.Activities.Statements.TryCatch> activity in the workflow, regardless of whether it is rethrown from that higher level <xref:System.Activities.Statements.TryCatch>.</span></span>  
  
- <span data-ttu-id="b3672-148">La excepción no la controla un <xref:System.Activities.Statements.TryCatch> de mayor nivel, se escapa la raíz del flujo de trabajo, y el flujo de trabajo se configura para cancelarse en lugar de finalizarse o anularse.</span><span class="sxs-lookup"><span data-stu-id="b3672-148">The exception is not handled by a higher level <xref:System.Activities.Statements.TryCatch>, escapes the root of the workflow, and the workflow is configured to cancel instead of terminate or abort.</span></span> <span data-ttu-id="b3672-149">Los flujos de trabajo hospedados mediante <xref:System.Activities.WorkflowApplication> pueden configurar esto controlando <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> y devolviendo <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="b3672-149">Workflows hosted using <xref:System.Activities.WorkflowApplication> can configure this by handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> and returning <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="b3672-150">Un ejemplo de cómo administrar <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> se proporciona anteriormente en este tema.</span><span class="sxs-lookup"><span data-stu-id="b3672-150">An example of handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> is provided previously in this topic.</span></span> <span data-ttu-id="b3672-151">Los servicios de flujo de trabajo pueden configurar esto mediante <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> y especificando <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="b3672-151">Workflow services can configure this by using <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> and specifying <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="b3672-152">Para obtener un ejemplo de configuración <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> , consulte [extensibilidad de host de servicio de flujo de trabajo](../wcf/feature-details/workflow-service-host-extensibility.md).</span><span class="sxs-lookup"><span data-stu-id="b3672-152">For an example of configuring <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, see [Workflow Service Host Extensibility](../wcf/feature-details/workflow-service-host-extensibility.md).</span></span>  
  
## <a name="exception-handling-versus-compensation"></a><span data-ttu-id="b3672-153">Control de excepciones contra compensación</span><span class="sxs-lookup"><span data-stu-id="b3672-153">Exception Handling versus Compensation</span></span>  

 <span data-ttu-id="b3672-154">La diferencia entre el control de excepciones y la compensación es que el primero se produce durante la ejecución de una actividad.</span><span class="sxs-lookup"><span data-stu-id="b3672-154">The difference between exception handling and compensation is that exception handling occurs during the execution of an activity.</span></span> <span data-ttu-id="b3672-155">La compensación, sin embargo, se produce después de que una actividad se haya completado correctamente.</span><span class="sxs-lookup"><span data-stu-id="b3672-155">Compensation occurs after an activity has successfully completed.</span></span> <span data-ttu-id="b3672-156">El control de excepciones proporciona una oportunidad para limpiar después de que la actividad produzca la excepción, mientras la compensación proporciona un mecanismo por el que se puede deshacer el trabajo terminado correctamente de una actividad completada previamente.</span><span class="sxs-lookup"><span data-stu-id="b3672-156">Exception handling provides an opportunity to clean up after the activity raises the exception, whereas compensation provides a mechanism by which the successfully completed work of a previously completed activity can be undone.</span></span> <span data-ttu-id="b3672-157">Para obtener más información, consulte [compensación](compensation.md).</span><span class="sxs-lookup"><span data-stu-id="b3672-157">For more information, see [Compensation](compensation.md).</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="b3672-158">Vea también</span><span class="sxs-lookup"><span data-stu-id="b3672-158">See also</span></span>

- <xref:System.Activities.Statements.TryCatch>
- <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>
- <xref:System.Activities.Statements.CompensableActivity>
